# Sales Service Configuration

# Environment (development, staging, production)
environment: "development"

# HTTP server configuration
server:
  address: "0.0.0.0:8080"
  timeout: 30s
  cors_enabled: true
  cors_origins: ["*"]

# Database configuration
database:
  dsn: "postgresql://postgres:postgres@postgres:5432/sales?sslmode=disable"
  read_only_dsn: "postgresql://postgres:postgres@postgres:5432/sales_readonly?sslmode=disable"
  name: "sales"
  max_open_conns: 50
  max_idle_conns: 10
  conn_max_lifetime: "1h"

# Redis configuration
redis:
  host: "redis"
  port: 6379
  password: ""
  db: 0
  enabled: true

# Azure Service Bus configuration
azure:
  queue_conn_str: "Endpoint=sb://localhost/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=dummy"
  queue_name: "sales-events"

# Elasticsearch configuration
elastic:
  url: "http://elasticsearch:9200"
  username: ""
  password: ""
  prefix: "sales"
  index: "sales"

# Tracing configuration (New Relic)
tracing:
  license_key: ""
  app_name: "Sales Service"
  log_level: "info"
  log_enabled: true
  distributed_tracing_enabled: true

# Metrics
metrics_enabled: true

# Logging configuration
logging:
  level: "info"  # debug, info, warn, error
  format: "json" # json, text