# Truck Operations Service Configuration

# Server configuration
server:
  host: "0.0.0.0"
  port: 8000
  read_timeout: "1m"
  write_timeout: "1m"
  shutdown_timeout: "10s"
  cors_white_list:
    - "*"

# Database configuration
database:
  host: "postgres"
  port: 5432
  user: "postgres"
  password: "postgres"
  name: "truck"
  ssl_mode: "disable"
  debug: false
  max_conn: 100
  max_idle: 10
  max_life: "5m"

# Message Bus configuration
message_bus:
  connection_string: "Endpoint=sb://localhost/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=dummy"
  prefix: "dev"
  queues:
    - "erp-operations"
    - "truck-events"
  erp_queue: "erp-messages-operations"

# Redis configuration
redis:
  host: "redis"
  port: 6379
  password: ""
  db: 1
  enabled: true

# Logging configuration
logging:
  level: "info"
  json: false

# API Versioning
api:
  version: "v1"
  prefix: "/api"